-- Create categories table
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security) if needed, or leave open for now based on existing patterns
-- For now, we assume public access or authenticated access handled by client
alter table categories enable row level security;
alter table categories 
  add column if not exists image_url text,
  add column if not exists description text;

-- Create policy to allow all operations for public (since this is a dashboard demo)
-- You might want to restrict this in production
drop policy if exists "Allow all operations for public" on categories;
create policy "Allow all operations for public" on categories
  for all using (true) with check (true);

insert into categories (name)
select v.name
from (values
  ('UNCATEGORIZED'),
  ('LCD'),
  ('Battery'),
  ('Flex / Port'),
  ('Camera'),
  ('Speaker'),
  ('Back Cover'),
  ('Board / IC'),
  ('Parts'),
  ('Tools'),
  ('Accessories')
) as v(name)
where not exists (
  select 1 from categories c where c.name = v.name
);
