-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create Products Table
create table if not exists products (
  id bigint generated by default as identity primary key,
  title text,
  name text, -- fallback for title
  price numeric default 0,
  sku text,
  stock integer default 0,
  images text[], -- Array of image URLs
  image_url text, -- Single image URL (legacy support)
  description text,
  features text[], -- Array of features
  sale_price numeric,
  discount_price numeric, -- fallback for sale_price
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table products add column if not exists category_id bigint references categories(id);


-- Enable RLS
alter table products enable row level security;

-- Policies
-- 1. Public Read Access (Required for Storefront)
drop policy if exists "Public can view products" on products;
create policy "Public can view products" on products
  for select using (true);

-- 2. Authenticated/Public Write Access (For Dashboard - simplified for demo)
-- Ideally this should be restricted to admins, but for this vanilla JS demo:
drop policy if exists "Allow all operations for public" on products;
create policy "Allow all operations for public" on products
  for all using (true) with check (true);
