-- Add new columns to categories table
-- Run this if you already created the table.
-- If you haven't created the table yet, you can just run the full CREATE TABLE statement below instead.

ALTER TABLE categories 
ADD COLUMN IF NOT EXISTS image_url text,
ADD COLUMN IF NOT EXISTS description text;

-- (Optional) If you are creating the table from scratch, use this:
/*
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table categories enable row level security;
create policy "Allow all operations for public" on categories for all using (true) with check (true);
*/
